name: Deploy to FTP
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:    
  minify-code:
    name: Minify
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - name: Get codebase
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Minify Action
        uses: anthonyftwang/minify-action@v1.0.1

      # Auto-commit to repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Minify source code
          branch: ${{ github.ref }}
