name: Deploy to FTP
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:    
  minify-code:
    name: Deploy assets
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - name: Get codebase
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Minify files
        uses: docker://devatherock/minify-js:1.0.3

      # Auto-commit to repository
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor: Minify source code"
          branch: ${{ github.ref }}
          
      - name: Get latest code
        uses: actions/checkout@v2
    
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./deploy/
          server-dir: assets/
