name: Deploy to FTP
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:    
  minify-code:
    name: Minify
    runs-on: ubuntu-latest
    steps:
      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:1.0.3
