name: Deploy to FTP
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:    
  minify-code:
    name: Minify JS and CSS
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - name: Get codebase
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Minify files
        uses: nizarmah/auto-minify@v2.1
        with:
          output: 'mini'

      # Auto-commit to repository
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: 'mini'
          commit_message: "refactor: Minify source code"
          branch: ${{ github.ref }}
