name: Inventory
on: 
  workflow_dispatch:

jobs:
  update-inventory:
    name: Update Inventory
    runs-on: ubuntu-latest
    steps:
      - name: Get codebase
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Download inventory files
        run: |
          mkdir data
          curl ${{ secrets.ftp_server }}/images/ImportExport/Inventory/LAGERBEHOLD.LST --user ${{ secrets.ftp_username }}:${{ secrets.ftp_password }} -s -o data/lagerbehold.LST
          curl ${{ secrets.ftp_server }}/images/ImportExport/Inventory/LAGERBEVAEG.LST --user ${{ secrets.ftp_username }}:${{ secrets.ftp_password }} -s -o data/lagerbevaeg.LST
          curl ${{ secrets.ftp_server }}/images/ImportExport/Inventory/VARER.LST --user ${{ secrets.ftp_username }}:${{ secrets.ftp_password }} -s -o data/varer.LST

      - name: Dotnet restore
        run: dotnet restore "InventoryService/InventoryService.csproj"

      - name: Dotnet build
        run: dotnet build "InventoryService/InventoryService.csproj" -c Release -o /app/build

      - name: Dotnet publish
        run: dotnet publish "InventoryService/InventoryService.csproj" -c Release -o /app/publish

      - name: Dotnet run
        run: dotnet run --project InventoryService

      - name: Echo file
        run: echo "$(<document.xml )"
