name: Inventory
on: 
  workflow_dispatch:
  schedule:
  - cron: "0 16 * * *"

jobs:
  update-inventory:
    name: Update Inventory
    runs-on: ubuntu-latest
    steps:
      - name: Get codebase
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Download inventory files
        run: |
          mkdir data
          curl ${{ secrets.ftp_server }}/images/ImportExport/Inventory/LAGERBEHOLD.LST --user "${{ secrets.ftp_username }}":"${{ secrets.ftp_password }}" -v -o data/lagerbehold.LST
          curl ${{ secrets.ftp_server }}/images/ImportExport/Inventory/LAGERBEVAEG.LST --user "${{ secrets.ftp_username }}":"${{ secrets.ftp_password }}" -v -o data/lagerbevaeg.LST
          curl ${{ secrets.ftp_server }}/images/ImportExport/Inventory/VARER.LST --user "${{ secrets.ftp_username }}":"${{ secrets.ftp_password }}" -v -o data/varer.LST
          readlink -f data/varer.LST

      - name: Dotnet run
        run: dotnet run --project InventoryService
        
      - name: Sync inventory file
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./data/
          server-dir: images/ImportExport/Inventory/Updated/

      - name: Update Inventory
        run: curl --location --request POST '${{ secrets.api_upload_endpoint }}?file=Inventory/Updated/document.xml&response=1&updateonly=1' --form 'user="${{ secrets.api_username }}"' --form 'password="${{ secrets.api_password }}"'
