name: Static code analysis

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build:
    name: Lint 
    runs-on: ubuntu-latest
    steps:
    - name: Get codebase
      uses: actions/checkout@v2
    - name: Setup node
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: eslint . --ext .js
